package surveybot

import (
	"fmt"
	"html"
	"sort"
	"strings"
	"time"
)

// RenderThemedHTML builds a self-contained FormsX-themed HTML report of survey answers.
func RenderThemedHTML(title string, answers map[string]string, templateTitle string) string {
	if title == "" {
		title = "Survey result"
	}
	keys := make([]string, 0, len(answers))
	for k := range answers {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var rows strings.Builder
	for _, k := range keys {
		v := answers[k]
		rows.WriteString(fmt.Sprintf(`
      <tr>
        <th scope="row">%s</th>
        <td>%s</td>
      </tr>`, html.EscapeString(prettyLabel(k)), html.EscapeString(v)))
	}
	if len(keys) == 0 {
		rows.WriteString(`<tr><td colspan="2" class="empty">No answers recorded.</td></tr>`)
	}

	when := time.Now().UTC().Format(time.RFC3339)
	sub := templateTitle
	if sub == "" {
		sub = "Survey Bot"
	}

	return fmt.Sprintf(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>%s</title>
<style>
  :root {
    --bg: #f5f8ff;
    --card: #ffffff;
    --text: #0f172a;
    --muted: #31566b;
    --accent: #0f4c66;
    --accent-soft: #d8eef8;
    --border: #b7deee;
    --row: #e8f5fb;
  }
  @media (prefers-color-scheme: dark) {
    :root {
      --bg: #0b1220;
      --card: #111827;
      --text: #e2e8f0;
      --muted: #94a3b8;
      --accent: #7dd3fc;
      --accent-soft: #0c4a6e;
      --border: #1e3a5f;
      --row: #0f172a;
    }
  }
  * { box-sizing: border-box; }
  body {
    margin: 0;
    font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif;
    background: linear-gradient(180deg, var(--bg), #eef6fb 60%%, var(--bg));
    color: var(--text);
    min-height: 100vh;
    padding: 2rem 1rem;
  }
  .wrap {
    max-width: 720px;
    margin: 0 auto;
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 16px;
    box-shadow: 0 10px 30px rgba(15, 76, 102, 0.08);
    overflow: hidden;
  }
  header {
    padding: 1.5rem 1.75rem 1.25rem;
    background: linear-gradient(135deg, var(--accent-soft), transparent 70%%);
    border-bottom: 1px solid var(--border);
  }
  .badge {
    display: inline-block;
    font-size: 0.75rem;
    font-weight: 600;
    letter-spacing: 0.04em;
    text-transform: uppercase;
    color: var(--accent);
    background: var(--accent-soft);
    border: 1px solid var(--border);
    border-radius: 999px;
    padding: 0.2rem 0.65rem;
    margin-bottom: 0.75rem;
  }
  h1 {
    margin: 0 0 0.35rem;
    font-size: 1.55rem;
    font-weight: 700;
    color: var(--accent);
  }
  .meta { margin: 0; color: var(--muted); font-size: 0.9rem; }
  table {
    width: 100%%;
    border-collapse: collapse;
  }
  th, td {
    text-align: left;
    padding: 0.9rem 1.75rem;
    vertical-align: top;
    border-bottom: 1px solid var(--border);
  }
  tr:nth-child(even) { background: var(--row); }
  th {
    width: 38%%;
    color: var(--muted);
    font-weight: 600;
    font-size: 0.92rem;
  }
  td { font-size: 1rem; }
  .empty { color: var(--muted); text-align: center; padding: 2rem; }
  footer {
    padding: 1rem 1.75rem 1.35rem;
    color: var(--muted);
    font-size: 0.8rem;
  }
</style>
</head>
<body>
  <div class="wrap">
    <header>
      <div class="badge">FormsX Survey Bot</div>
      <h1>%s</h1>
      <p class="meta">Template: %s · Saved %s</p>
    </header>
    <table>
      <tbody>
        %s
      </tbody>
    </table>
    <footer>Generated by FormsX Survey Bot · theme-aligned report</footer>
  </div>
</body>
</html>`,
		html.EscapeString(title),
		html.EscapeString(title),
		html.EscapeString(sub),
		html.EscapeString(when),
		rows.String(),
	)
}

func prettyLabel(field string) string {
	field = strings.ReplaceAll(field, "_", " ")
	if field == "" {
		return "Field"
	}
	parts := strings.Fields(field)
	for i, p := range parts {
		if len(p) == 0 {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, " ")
}

// FormatAnswersMarkdown renders a live session summary of collected answers.
func FormatAnswersMarkdown(answers map[string]string) string {
	if len(answers) == 0 {
		return "_No answers yet._"
	}
	keys := make([]string, 0, len(answers))
	for k := range answers {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString("**Collected so far**\n")
	for _, k := range keys {
		b.WriteString(fmt.Sprintf("- **%s:** %s\n", prettyLabel(k), answers[k]))
	}
	return strings.TrimSpace(b.String())
}
