package db

// MorphOwnedTablesFKOrder is the FK-safe copy order for MySQL → SQLite migration.
// See openspec/changes/morph-embedded-dbs/inventory.md.
var MorphOwnedTablesFKOrder = []string{
	"District",
	"User",
	"plat_users",
	"contact",
	"facility",
	"member",
	"employee",
	"Asset",
	"Activity",
	"ActivityEmployee",
	"ActivityParticipant",
	"ActivityAsset",
	"CaseTask",
	"CaseTaskAssignee",
	"StoryPost",
	"comment",
	"generic_data",
	"EntityAttachment",
	"AdminGridSavedFilter",
	"AdminGridColorConfig",
	"PlatformUiConfig",
	"user_note_todo",
	"record_contact",
	"tool_note",
	"tool_broadcast",
	"big_note",
	"big_note_response",
	"timeline",
	"morph_knowledge_files",
	"morph_knowledge_chunks",
	"graph_sync_outbox",
	"neo4j_ingest_outbox",
	"ai_skills",
	"StaffType",
	"StaffStaffType",
	"email_agent",
	"email_agent_log",
	"user_message_auto_reply_log",
}
