#!/usr/bin/env bash
# One-shot: copy non-empty keys from known per-app .env files into repo-root .env.
# Does not overwrite an existing root .env. Last non-empty value wins; Morph is applied last.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="${ROOT}/.env"

if [[ -f "$DEST" ]]; then
  echo "Refusing to overwrite existing ${DEST}" >&2
  exit 1
fi

SOURCES=(
  "${ROOT}/formx/backend/.env"
  "${ROOT}/composerx/backend/.env"
  "${ROOT}/composerx/frontend/.env"
  "${ROOT}/booki/.env"
  "${ROOT}/booki/frontend/.env"
  "${ROOT}/academi/backend/.env"
  "${ROOT}/morph-engi/.env"
  "${ROOT}/SharpReport/.env"
  "${ROOT}/bk/.env"
  "${ROOT}/bk/frontend/.env"
  "${ROOT}/morph/frontend/.env"
  "${ROOT}/morph/frontend/.env.local"
  "${ROOT}/morph/.env"
)

STASH="$(mktemp -d)"
ORDER="$(mktemp)"
trap 'rm -rf "$STASH" "$ORDER"' EXIT

ingest() {
  local envfile="$1"
  [[ -f "$envfile" ]] || return 0
  local line key value
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line%$'\r'}"
    [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
    if [[ "$line" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]]; then
      key="${BASH_REMATCH[1]}"
      value="${BASH_REMATCH[2]}"
      value="${value%$'\r'}"
      if [[ "$value" =~ ^\"(.*)\"$ ]]; then
        value="${BASH_REMATCH[1]}"
      elif [[ "$value" =~ ^\'(.*)\'$ ]]; then
        value="${BASH_REMATCH[1]}"
      fi
      [[ -z "$value" ]] && continue
      case "$envfile" in
        *"/composerx/backend/.env") [[ "$key" == PORT ]] && key=COMPOSERX_PORT ;;
        *"/academi/backend/.env") [[ "$key" == SERVER_PORT ]] && key=ACADEMI_SERVER_PORT ;;
        *"/morph-engi/.env")
          [[ "$key" == APP_PORT ]] && key=MORPH_ENGI_PORT
          [[ "$key" == DATABASE_URL ]] && key=MORPH_ENGI_DATABASE_URL
          [[ "$key" == CORS_ORIGIN ]] && key=MORPH_ENGI_CORS_ORIGIN
          ;;
        *"/SharpReport/.env")
          [[ "$key" == PORT ]] && key=SHARPREPORT_PORT
          [[ "$key" == DATABASE_URL ]] && key=SHARPREPORT_DATABASE_URL
          ;;
      esac
      printf '%s' "$value" >"${STASH}/${key}"
      if ! grep -qx "$key" "$ORDER" 2>/dev/null; then
        printf '%s\n' "$key" >>"$ORDER"
      fi
    fi
  done <"$envfile"
}

for src in "${SOURCES[@]}"; do
  ingest "$src"
done

{
  echo "# Generated by scripts/merge-local-env.sh — edit as needed."
  echo "# See .env.example for the full key catalog."
  echo
  n=0
  while IFS= read -r key || [[ -n "$key" ]]; do
    [[ -z "$key" ]] && continue
    printf '%s=%s\n' "$key" "$(cat "${STASH}/${key}")"
    n=$((n + 1))
  done <"$ORDER"
} >"$DEST"

echo "Wrote ${DEST}"
